#!/bin/sh

umask 022
test -d package || sh -cx '! : Wrong working directory.'
test -d man || sh -cx '! : Wrong working directory.'

echo 'Compressing manpages...'
for i in man/*.[1-8]; do
  gzip -c $i >${i}.gz
done

echo 'Installing into /usr/local/man...'
cd man
for i in 8; do
  mkdir -p /usr/local/man/man$i
  for j in *.$i; do
    mv -uv $j.gz /usr/local/man/man$i/$j.gz
    rm -f $j.gz
  done
done
cd ..
