#!/bin/sh
## Copyright 2018 Dmitry Bogatov <KAction@gnu.org>
## 
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

for ix in $(seq 6) ; do
    service_dir="debian/auto/getty-tty${ix}"
    template_dir="debian/getty.in"
    mkdir -p "${service_dir}"
    for script in run finish ; do
        sed "s/@TTY@/tty${ix}/g" \
            "${template_dir}/${script}.in" > "${service_dir}/${script}"
        chmod +x "${service_dir}/${script}"
    done
done
