runit-*/doc/*[a-z].html     /usr/share/doc/runit/html
debian/contrib/update-service        /sbin

debian/contrib/runscript /usr/bin

runit-*/src/runsvdir   /usr/bin
runit-*/src/runsv      /usr/bin
runit-*/src/sv         /usr/bin
runit-*/src/svlogd     /usr/bin
runit-*/src/chpst      /usr/bin
runit-*/src/runsvchdir /usr/sbin
runit-*/src/utmpset    /usr/sbin

debian/contrib/1       /etc/runit
debian/contrib/2       /etc/runit
debian/contrib/3       /etc/runit
