runit-*/doc/*[a-z].html     /usr/share/doc/runit/html
debian/contrib/update-service        /sbin

runit-*/src/runsvdir   /usr/bin
runit-*/src/runsv      /usr/bin
runit-*/src/sv         /usr/bin
runit-*/src/svlogd     /usr/bin
runit-*/src/chpst      /usr/bin
runit-*/src/runsvchdir /usr/sbin
runit-*/src/utmpset    /usr/sbin

runit-*/etc/debian/1   /etc/runit
runit-*/etc/2          /etc/runit
runit-*/etc/debian/3   /etc/runit