.TH RUNLEVEL 8 "Oct 10, 2016" "" "GNU/Linux System Adminstrator's manual"
.SH NAME
runlevel \- SysV-init compatibility layer
.SH SYNOPSIS
.B /sbin/runlevel
.SH DESCRIPTION
This program always print literate
.I `N
.I 2'
string, which is for compatibility with
.B update-rc.d
program.
.SH SEE ALSO
.BR update-rc.d (8)
