.\" Copyright (C), 2017  Dmitry Bogatov
.\" You may distribute this file under the terms of the GNU Free
.\" Documentation License.
.TH runscript 1 2017-01-19
.SH NAME
runscript \- generate service scripts for runit
.SH SYNOPSIS
.B runscript
[--add|--remove] unprivilleged
.I USER
.SH DESCRIPTION
Add or remove runscript into directory, specified by SVDIR environment
variable. List of supported runscripts see below. These runscripts are
too site-specific, so it is impossible to put them into binary
package.

If SVDIR is not set and current user is not root, then
.I ~/.service
directory is used. If current user is root, SVDIR defaults to
.I /etc/service.

.SS unprivilleged
Makes sense only when invoked by root. Setup runscript, that control
.B runsvdir
process, which belong to specified user and manages services, specified
in user's
.I ~/.service
directory.
.SH "SEE ALSO"
.BR runsvdir (8)
.SH AUTHOR
Dmitry Bogatov <KAction@gnu.org>
