.TH SHUTDOWN 8 "Oct 10, 2016" "" "GNU/Linux System Adminstrator's manual"
.SH NAME
shutdown, reboot, poweroff \- stop the system
.SH SYNOPSIS
.B /sbin/shutdown
.br
.B /sbin/reboot
.br
.B /sbin/halt
.SH DESCRIPTION
SysV-init compatibility scripts, that just invokes
.BR /sbin/init ,
which are expected by graphical desktop environments.
.SH SEE ALSO
.BR init (8)
